/**
 * Auth wiring + admin-triggered password reset flow.
 *
 * - `auth`, `signIn`, `signOut`, `store`, `isAuthenticated` are generated by
 *   `@convex-dev/auth` from the Password provider.
 * - `consumePasswordResetFlag` (internal mutation) and `resetFlaggedPassword`
 *   (public action) implement an admin-initiated password reset where the
 *   admin flips `users.passwordResetPending` to `true` via the Convex
 *   dashboard and the user then sets their own new password via the sign-in
 *   page. The admin never sees the password and the user's `users._id` is
 *   preserved across the reset.
 *
 * See `plans/2026-05-16-admin-password-reset-flag-v1.md`.
 */

import { Password } from "@convex-dev/auth/providers/Password";
import {
  convexAuth,
  invalidateSessions,
  modifyAccountCredentials,
} from "@convex-dev/auth/server";
import { v } from "convex/values";
import { internal } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { action, internalMutation } from "./_generated/server";

export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
  providers: [Password],
});

/**
 * Atomically validates that an admin-issued password reset is pending for
 * the given email and clears the flag. Throws a deliberately uniform
 * `"No reset pending."` error for every failure case (no such user, the
 * email matches multiple rows, flag absent) to avoid account-enumeration
 * leaks from the unauthenticated action that wraps this mutation.
 *
 * Returns the matched `users._id` so the caller can invalidate any
 * lingering sessions without a second lookup. Internal because no client
 * may call this directly; only `resetFlaggedPassword` consumes it.
 */
export const consumePasswordResetFlag = internalMutation({
  args: { email: v.string() },
  handler: async (ctx, { email }): Promise<Id<"users">> => {
    const matches = await ctx.db
      .query("users")
      .withIndex("email", (q) => q.eq("email", email))
      .take(2);
    // Email lookup is case-sensitive and not trimmed; matches what the
    // Password provider's sign-in path does (`Password.js:56-67`). See
    // `plans/2026-05-16-admin-password-reset-flag-v1.md` §Assumptions.
    if (matches.length === 0) {
      throw new Error("No reset pending.");
    }
    if (matches.length >= 2) {
      // Multiple users share this email (Convex has no schema-level
      // uniqueness and this project does not run email verification).
      // The admin must resolve the duplicate via the dashboard before
      // retrying; silently picking row #0 would be a footgun.
      throw new Error("No reset pending.");
    }
    const user = matches[0];
    if (user.passwordResetPending !== true) {
      throw new Error("No reset pending.");
    }
    await ctx.db.patch(user._id, { passwordResetPending: undefined });
    return user._id;
  },
});

/**
 * Public, unauthenticated endpoint used by the "Forgot password?" flow on
 * the sign-in page. Succeeds only when an admin has flipped
 * `users.passwordResetPending` to `true` via the dashboard for the matched
 * email.
 *
 * Flow:
 *   1. Reject obviously-invalid passwords (< 8 chars) BEFORE consuming
 *      the flag, so a single typo is retryable.
 *   2. Atomically consume the flag (the mutation also performs the user
 *      lookup; the flag is cleared in the same transaction).
 *   3. Overwrite the password hash via `modifyAccountCredentials` (uses
 *      the Password provider's Scrypt hasher — the new secret is
 *      indistinguishable on disk from a sign-up secret). Library errors
 *      are masked because `modifyAccount.js:22` echoes the email back
 *      verbatim, which would leak the address from this unauthenticated
 *      endpoint.
 *   4. Invalidate any pre-existing sessions for the user. Mirrors the
 *      library's built-in reset-verification flow (`Password.js:118`),
 *      which calls `invalidateSessions(..., { except: [sessionId] })`
 *      to preserve the just-created session. We have no current session
 *      to preserve (the action is unauthenticated), so we kill all of
 *      them.
 *
 * Note: the failure-mode response times are not uniform. The "no user"
 * branch returns after a single index lookup; the "flag set but no
 * authAccounts row" branch goes through flag consumption and a second
 * mutation round-trip before the masked throw. Acceptable for the
 * documented trust model; rate-limit before exposing this endpoint to
 * untrusted networks.
 *
 * If step 3 throws (e.g. the user has the flag set but no `authAccounts`
 * row for the Password provider — possible in a hypothetical future
 * multi-provider deployment), the flag is already consumed and the admin
 * must re-flip it. Acceptable for the small-trusted-group threat model
 * since no auth state leaks during the window.
 */
export const resetFlaggedPassword = action({
  args: { email: v.string(), newPassword: v.string() },
  handler: async (ctx, { email, newPassword }): Promise<null> => {
    if (newPassword.length < 8) {
      throw new Error("Password must be at least 8 characters.");
    }
    const userId: Id<"users"> = await ctx.runMutation(
      internal.auth.consumePasswordResetFlag,
      { email },
    );
    try {
      await modifyAccountCredentials(ctx, {
        provider: "password",
        account: { id: email, secret: newPassword },
      });
    } catch (e) {
      // The library's underlying error
      // (`"Cannot modify account with ID ${id} because it does not exist"`,
      // `modifyAccount.js:22`) echoes the email back to the unauthenticated
      // caller. Mask it. Log the original for ops visibility.
      console.error(
        "resetFlaggedPassword: modifyAccountCredentials threw after flag consumption:",
        e,
      );
      throw new Error("No reset pending.");
    }
    await invalidateSessions(ctx, { userId });
    return null;
  },
});
